[workspace]
resolver = "2"
members = [
    "embedcore-sys",
    "embedcore",
    "embedcore-mcp",
]

[workspace.dependencies]
cc = "1.0"
libc = "0.2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
